hackathonistas/hackathonistas.github.io

index.html
just the basic html boilerplate to check whether its working.
=> Initialising HTML

index.html
Added the telegram joinchat link.
=> Added telegram href link

about.html, css/about.css, css/index.css, index.html
1. Added the link to about.html on index.html
2. Fixed the h1 padding issue on index.html https://github.com/hackathonistas/hackathonistas.github.io/issues/9
3. Added Mobile Compatibility on about.html https://github.com/hackathonistas/hackathonistas.github.io/issues/8
=> Added about link on index and fixed 2 issues

css/headers.css, css/index.css
Improved mobile compatibility. 
* the team section now collapses into groups of 2 and then single cards
* the home section collapses at 800px, it was better that way
=> improve mobile compatibilty

css/headers.css
Improved mobile compatibility. 
* the team section now collapses into groups of 2 and then single cards
* the home section collapses at 800px, it was better that way
=> minor changes

css/hackathons.css, hackathons.html, js/main.js
Added upcoming hackathon card. This is half of the work of the page. The JS part and integration with firebase is left.
=> Add upcoming hackathon card

hackathons.html, js/main.js
Added initial firebase functionality to pull hackathon information and add a card in the UI corresponding to every hackathon.
=> Added initial firebase functionality

css/hackathons.css
There is now space for a 3rd one on every column.
=> Changed css to make 3 hackathons display in a row

hackathons.html, js/main.js
=> Added spinner + removed the first placeholder card

js/main.js
=> Made the word "organizer" bold

index.html
=> Added my email to index.html

css/index.css, hackathons.html, index.html
Added code of conduct on the index page and also added the download link
Closes https://github.com/hackathonistas/hackathonistas.github.io/issues/36
=> add code of conduct html

css/hackathons.css, js/main.js
=> Added show-hide functionality for descriptions + consistent title height

hackathons.html, index.html, js/firebase.js, js/login.js, js/main.js, login.html
- broke up js files and included persistent firebase functionality in one file, firebase.js
- created login.js for login functionality
- added login.html
=> Added login functionality

js/login.js, login.html
- changed id="show_signup_box" to class="box_toggle" and made corresponding changes in login.js to keep the toggle working
=> Fixed login/signup box toggle to keep functionality consistent

css/headers.css, css/settings.css, js/firebase.js, js/login.js, js/settings.js, settings.html
- Buttons in the navbar related to account functionality are now grouped into a dropdown, including the sign out button
- Account related buttons like login/account drop down are right aligned.
=> Created dropdown for Accounts

add_hackathon.html, css/add_hackathon.css, css/hackathons.css, hackathons.html, js/add_hackathons.js
- Created add_hackathon.html, .css and .js
- Slighlty changed the html and css for the add new hackathon button to convert it to a proper href link
=> Created add new hackathon page

js/add_hackathons.js
Changed count trigger event from keydown to input to stop the event from firing at the wrong time
=> Changed count trigger event

js/firebase.js, js/pending_hackathons.js, pending_hackathons.html
=> Added special admin page for approving new hackathons

css/headers.css, css/login.css, hackathons.html, login.html
=> Fix for login button overlapping in the navbar

css/hackathons.css, js/main.js, js/settings.js, settings.html
- Made changes to main.js to implement functionality for the "Find teammates" button.
- The button:-
- prompts to login
- prompts to accept an agreement to make the user's email public
- when clicked, shows a list of users interested in finding teammates. The list features email links with sample invite messages.
- Settings.js was updated to include a section for user's to revoke permissions to make their email public for every hackathon separately.
=> Added "Find teammates" feature
